#! usr/bin/env php
<?php

namespace Creational\Prototype;

require_once 'vendor/autoload.php';

$firstPrototype = new Prototype();

$firstPrototype->getPrototype();
printf("%s \n", Prototype::$count);

$firstPrototype->getPrototype();
printf("%s \n", Prototype::$count);

$firstPrototype->getPrototype();
printf("%s \n", Prototype::$count);
